image: $SKA_K8S_TOOLS_BUILD_DEPLOY

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  NODE_IMAGE: 'node:22'
  CYPRESS_IMAGE: 'cypress/browsers:22.12.0'
  YARN_VERSION: '4.3.1'
  JS_E2E_TESTS_DIR: cypress

stages:
  - dependencies
  - lint
  - build
  #- test
  - scan
  #- pages
  # - integration
  # - staging
  # - deploy
  #- accessibility
  - publish

js-test:
  allow_failure: true
  before_script:
    - mkdir -p build/reports
  script:
    - yarn install
    - yarn test:unit --reporter junit --output-file build/reports/unit-tests.xml
  cache:
    paths:
      - node_modules/
    policy: pull
  artifacts:
    when: always
    reports:
      junit: build/reports/unit-tests.xml
    paths:
      - build/reports
    expire_in: 7 days

ts-typecheck:
  image: $NODE_IMAGE
  stage: lint
  needs: []
  allow_failure: true
  before_script:
    - make js-install
  script:
    - make typecheck

include:
  # TS linting and unit testing
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/js.gitlab-ci.yml'
  # .post step finalisers eg: badges
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'
