apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Chart.Name }}-nginx
  labels:
    {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $.Chart.Name }}
  template:
    metadata:
      labels:
        {{ include "labels" . | indent 8 }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.container }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 60
