apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}-service
  labels:
{{ include "labels" . | indent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  clusterIP: None
  selector:
{{ include "labels" . | indent 4 }}
